# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
update_fastlane

default_platform(:mac)

platform :mac do
  lane :format do
    Dir.chdir("..") do
      sh "swift-format format -i -r -p ."
    end
  end
end
